### PR TITLE
fix: should show menu icon conditionally 

### PR DESCRIPTION
**Pull request by a-m-dev**
defining prop of `shouldShowMenuIcon` which is responsible to hid/show menu button. 

default is `true`

### CODE REVIEW

**Comment by a-m-dev** [comment]
#deploy-me

**Review by cbt1 — APPROVED** [review]

**Comment by a-m-dev** [comment]
#deploy-me

**Comment by a-m-dev** [comment]
#deploy-me

**Comment by a-m-dev** [comment]
#deploy-me

**Comment by a-m-dev** [comment]
#deploy-me

**Comment by a-m-dev** [comment]
#deploy-me

**Pull request merged**
